server:
    port: 6661
eureka:
    #实例微服务端配置
    instance:
        #与此实例相关联的主机名，是其他实例可以用来进行请求的准确名称
        hostname: demo-registry
    server:
        #自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式
        #即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
        enable-self-preservation: false #关闭保护模式，清理断开的服务
        #清理任务程序被唤醒的时间间隔，清理过期的增量信息，单位为毫秒，默认为30 * 1000
        eviction-interval-timer-in-ms: 3000
    client:
        #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
        register-with-eureka: false
        #eureka服务注册表信息里的以逗号隔开的地区名单，如果不这样返回这些地区名单，则客户端启动将会出错。默认为null
        fetch-registry: false
        #注册中心地址配置
        serviceUrl:
            #注册中心默认地址，这里可以填写其他注册中心地址，做注册中心的高可用
            defaultZone: http://localhost:6661/eureka/